/**
 * BUSINESS KNOWLEDGE SUPERBASE
 * [Apphia.Logic] — Core Knowledge Layer
 *
 * Backend-only. Never imported by frontend pages directly.
 * Powers the Diagnosis Engine, Advisory Layer, and System Chains
 * via framework-to-signal mapping and canonical source attribution.
 *
 * Continuously updated with insights, lessons learned, and best practices.
 *
 * Domains:
 *  1. Corporate Strategy & Leadership
 *  2. Operations & Process Management
 *  3. Project, Program & Portfolio Management
 *  4. Finance & Accounting
 *  5. Marketing, Sales & Customer Strategy
 *  6. Human Capital & Organization
 *  7. Technology, Data & Digital Transformation
 *  8. Risk, Compliance & Governance
 */

// ── Types ────────────────────────────────────────────────────────────────────

export type KnowledgeDomain =
  | "Corporate Strategy & Leadership"
  | "Operations & Process Management"
  | "Project, Program & Portfolio Management"
  | "Finance & Accounting"
  | "Marketing, Sales & Customer Strategy"
  | "Human Capital & Organization"
  | "Technology, Data & Digital Transformation"
  | "Risk, Compliance & Governance";

export type DiagnosticRelevance =
  | "Signal Detection"
  | "Diagnosis"
  | "Advisory"
  | "Structural Remedy"
  | "Maturity Scoring"
  | "Dependency Intelligence"
  | "Action Generation";

export interface CanonicalSource {
  id: string;
  title: string;
  authors: string[];
  year: string; // "Latest edition" | "YYYY"
  domain: KnowledgeDomain;
  keyContribution: string;
  diagnosticRelevance: DiagnosticRelevance[];
  linkedFrameworks: string[];       // framework IDs from frameworkData.ts
  linkedSignalCategories: string[]; // signal categories from signals.ts
  linkedSystemChains: string[];     // system chain IDs from systemChains.ts
  tags: string[];
}

export interface KnowledgeLesson {
  id: string;
  sourceId: string;
  lesson: string;
  applicableTo: string[];  // module names
  addedAt: string;
}

export interface BestPractice {
  id: string;
  title: string;
  description: string;
  domain: KnowledgeDomain;
  frameworks: string[];
  applicableTo: string[];
  evidence: string;
}

// ── Domain 1: Corporate Strategy & Leadership ─────────────────────────────

const STRATEGY_SOURCES: CanonicalSource[] = [
  {
    id: "src-porter-cs",
    title: "Competitive Strategy",
    authors: ["Michael E. Porter"],
    year: "1980",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Introduced Five Forces framework to analyze industry competitiveness and strategy formulation",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["porter-five-forces", "porter-value-chain"],
    linkedSignalCategories: ["Strategic Misalignment", "Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-strategic-risk"],
    tags: ["five forces", "industry analysis", "competitive positioning"],
  },
  {
    id: "src-porter-ca",
    title: "Competitive Advantage",
    authors: ["Michael E. Porter"],
    year: "1985",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Explores value chain analysis and sustainable competitive advantage",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["porter-value-chain", "vrio"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["value chain", "competitive advantage", "differentiation"],
  },
  {
    id: "src-porter-oc",
    title: "On Competition",
    authors: ["Michael E. Porter"],
    year: "1998",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Collection of essays expanding on strategy concepts and competitive dynamics",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["porter-five-forces"],
    linkedSignalCategories: ["Strategic Misalignment", "Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["competitive dynamics", "industry strategy"],
  },
  {
    id: "src-kim-bos",
    title: "Blue Ocean Strategy",
    authors: ["W. Chan Kim", "Renée Mauborgne"],
    year: "2005",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Methodology for creating uncontested market space and value innovation",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["blue-ocean-strategy"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-innovation-pipeline", "sc-strategic-alignment"],
    tags: ["value innovation", "market creation", "differentiation"],
  },
  {
    id: "src-rumelt-gsbs",
    title: "Good Strategy Bad Strategy",
    authors: ["Richard Rumelt"],
    year: "2011",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Distinguishes effective strategies from poor ones with diagnostic frameworks",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["strategy-kernel"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-strategic-planning"],
    tags: ["strategy kernel", "strategic clarity", "execution alignment"],
  },
  {
    id: "src-lafley-ptw",
    title: "Playing to Win: How Strategy Really Works",
    authors: ["A.G. Lafley", "Roger Martin"],
    year: "2013",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Step-by-step guide to strategic choice cascades in organizations",
    diagnosticRelevance: ["Diagnosis", "Advisory", "Structural Remedy"],
    linkedFrameworks: ["strategic-choice-cascade"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-strategic-planning"],
    tags: ["choice cascade", "strategic decisions", "where to play"],
  },
  {
    id: "src-magretta-porter",
    title: "Understanding Michael Porter: The Essential Guide",
    authors: ["Joan Magretta"],
    year: "2011",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Simplifies Porter's concepts for practical strategic application",
    diagnosticRelevance: ["Diagnosis"],
    linkedFrameworks: ["porter-five-forces", "porter-value-chain"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["competitive strategy", "practical application"],
  },
  {
    id: "src-dixit-art-of-strategy",
    title: "The Art of Strategy",
    authors: ["Avinash K. Dixit", "Barry J. Nalebuff"],
    year: "2008",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Applies game theory to competitive and business decisions",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["decision-trees", "scenario-planning"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-decision-support", "sc-strategic-risk"],
    tags: ["game theory", "competitive decisions", "strategic thinking"],
  },
  {
    id: "src-collins-gtg",
    title: "Good to Great",
    authors: ["Jim Collins"],
    year: "2001",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Identifies factors that transform good companies into great performers",
    diagnosticRelevance: ["Maturity Scoring", "Advisory"],
    linkedFrameworks: ["operational-maturity-models"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-org-health", "sc-performance-benchmarking"],
    tags: ["organizational excellence", "disciplined execution", "flywheel"],
  },
  {
    id: "src-collins-btl",
    title: "Built to Last",
    authors: ["Jim Collins", "Jerry Porras"],
    year: "1994",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Investigates long-lasting corporate practices for enduring success",
    diagnosticRelevance: ["Maturity Scoring", "Structural Remedy"],
    linkedFrameworks: ["balanced-scorecard", "operational-maturity-models"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-org-health"],
    tags: ["core ideology", "visionary companies", "long-term success"],
  },
  {
    id: "src-peters-isoe",
    title: "In Search of Excellence",
    authors: ["Tom Peters", "Robert H. Waterman Jr."],
    year: "1982",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Analyzes successful companies to extract management principles",
    diagnosticRelevance: ["Diagnosis", "Maturity Scoring"],
    linkedFrameworks: ["mckinsey-7s"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-org-health"],
    tags: ["excellence", "management principles", "organizational culture"],
  },
  {
    id: "src-kaplan-bsc",
    title: "The Balanced Scorecard: Translating Strategy into Action",
    authors: ["Robert Kaplan", "David Norton"],
    year: "1996",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Connects strategic objectives to measurable performance indicators",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Maturity Scoring"],
    linkedFrameworks: ["balanced-scorecard"],
    linkedSignalCategories: ["Strategic Misalignment", "KPI Underperformance", "Performance Degradation"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-performance-management", "sc-org-health"],
    tags: ["strategy execution", "KPIs", "four perspectives", "performance measurement"],
  },
  {
    id: "src-mintzberg-safari",
    title: "Strategy Safari",
    authors: ["Henry Mintzberg", "Bruce Ahlstrand", "Joseph Lampel"],
    year: "1998",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Explores ten schools of thought in strategy formulation",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["strategy-kernel", "scenario-planning"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-planning"],
    tags: ["strategy schools", "emergent strategy", "deliberate strategy"],
  },
  {
    id: "src-daveni-cd",
    title: "Competitive Dynamics",
    authors: ["Richard D'Aveni"],
    year: "1994",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Examines the dynamics of hypercompetitive markets",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["porter-five-forces", "scenario-planning"],
    linkedSignalCategories: ["Strategic Opportunity", "Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-risk"],
    tags: ["hypercompetition", "dynamic strategy", "market disruption"],
  },
  {
    id: "src-david-smc",
    title: "Strategic Management: Concepts and Cases",
    authors: ["Fred David"],
    year: "1997",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Combines theory with case studies for strategic decision making",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["swot-analysis", "balanced-scorecard"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-planning"],
    tags: ["strategic management", "case studies", "SWOT"],
  },
  {
    id: "src-mcgrath-eca",
    title: "The End of Competitive Advantage",
    authors: ["Rita Gunther McGrath"],
    year: "2013",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Argues that sustainable competitive advantage is rare in dynamic markets",
    diagnosticRelevance: ["Advisory", "Signal Detection"],
    linkedFrameworks: ["scenario-planning", "blue-ocean-strategy"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-risk", "sc-innovation-pipeline"],
    tags: ["transient advantage", "reconfiguration", "strategic agility"],
  },
  {
    id: "src-christensen-is",
    title: "The Innovator's Solution",
    authors: ["Clayton Christensen", "Michael Raynor"],
    year: "2003",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Explains how companies can create disruptive innovation",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["disruptive-innovation-model", "horizon-1-3-innovation"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-innovation-pipeline"],
    tags: ["disruption", "sustaining innovation", "market entry"],
  },
  {
    id: "src-treacy-dml",
    title: "The Discipline of Market Leaders",
    authors: ["Michael Treacy", "Fred Wiersema"],
    year: "1995",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Defines value disciplines for market leadership",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["strategic-choice-cascade"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["operational excellence", "customer intimacy", "product leadership"],
  },
  {
    id: "src-collis-cs",
    title: "Corporate Strategy: Resources and the Scope of the Firm",
    authors: ["David Collis", "Cynthia Montgomery"],
    year: "1997",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Focuses on resource-based view of strategy",
    diagnosticRelevance: ["Diagnosis"],
    linkedFrameworks: ["vrio"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["resource-based view", "capabilities", "competitive advantage"],
  },
  {
    id: "src-ringland-sp",
    title: "Scenario Planning: Managing for the Future",
    authors: ["Gill Ringland"],
    year: "1998",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Framework for planning under uncertainty",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["scenario-planning"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-risk", "sc-strategic-planning"],
    tags: ["scenario planning", "uncertainty", "futures thinking"],
  },
  {
    id: "src-mckeown-sb",
    title: "The Strategy Book",
    authors: ["Max McKeown"],
    year: "2012",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Practical guide to strategic thinking and execution",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["balanced-scorecard", "strategy-kernel"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-planning"],
    tags: ["strategic thinking", "practical strategy"],
  },
  {
    id: "src-bradley-sbhs",
    title: "Strategy Beyond the Hockey Stick",
    authors: ["Chris Bradley", "Martin Hirt", "Sven Smit"],
    year: "2018",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Data-driven strategic insight model",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["balanced-scorecard", "scenario-planning"],
    linkedSignalCategories: ["Performance Degradation", "Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-planning", "sc-performance-benchmarking"],
    tags: ["data-driven strategy", "big moves", "social dynamics"],
  },
  {
    id: "src-raynor-paradox",
    title: "The Strategy Paradox",
    authors: ["Michael Raynor"],
    year: "2007",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Balancing commitment and flexibility in uncertain environments",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["scenario-planning", "real-options"],
    linkedSignalCategories: ["Strategic Opportunity", "Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-risk"],
    tags: ["strategic commitment", "uncertainty management", "flexibility"],
  },
  {
    id: "src-slywotzky-vm",
    title: "Value Migration",
    authors: ["Adrian Slywotzky"],
    year: "1995",
    domain: "Corporate Strategy & Leadership",
    keyContribution: "Framework for understanding shifts in value across sectors",
    diagnosticRelevance: ["Signal Detection", "Advisory"],
    linkedFrameworks: ["bcg-growth-share", "porter-value-chain"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["value migration", "business design", "market shifts"],
  },
];

// ── Domain 2: Operations & Process Management ─────────────────────────────

const OPERATIONS_SOURCES: CanonicalSource[] = [
  {
    id: "src-womack-mctw",
    title: "The Machine That Changed the World",
    authors: ["James P. Womack", "Daniel T. Jones", "Daniel Roos"],
    year: "1990",
    domain: "Operations & Process Management",
    keyContribution: "History of lean production and industry transformation",
    diagnosticRelevance: ["Diagnosis", "Structural Remedy"],
    linkedFrameworks: ["lean", "value-stream-mapping"],
    linkedSignalCategories: ["Operational Bottleneck", "Capacity Overload"],
    linkedSystemChains: ["sc-operational-bottleneck", "sc-process-improvement"],
    tags: ["lean production", "toyota production system", "manufacturing"],
  },
  {
    id: "src-liker-tw",
    title: "The Toyota Way",
    authors: ["Jeffrey Liker"],
    year: "2004",
    domain: "Operations & Process Management",
    keyContribution: "14 principles behind Toyota's lean culture and operations",
    diagnosticRelevance: ["Diagnosis", "Structural Remedy"],
    linkedFrameworks: ["lean", "kaizen"],
    linkedSignalCategories: ["Operational Bottleneck", "Execution Breakdown"],
    linkedSystemChains: ["sc-operational-bottleneck", "sc-process-improvement"],
    tags: ["toyota principles", "continuous improvement", "lean culture"],
  },
  {
    id: "src-ohno-tps",
    title: "Toyota Production System: Beyond Large-Scale Production",
    authors: ["Taiichi Ohno"],
    year: "1988",
    domain: "Operations & Process Management",
    keyContribution: "Origins of lean manufacturing and just-in-time production",
    diagnosticRelevance: ["Diagnosis"],
    linkedFrameworks: ["lean", "value-stream-mapping", "kaizen"],
    linkedSignalCategories: ["Operational Bottleneck"],
    linkedSystemChains: ["sc-operational-bottleneck"],
    tags: ["JIT", "waste elimination", "pull systems"],
  },
  {
    id: "src-goldratt-goal",
    title: "The Goal",
    authors: ["Eliyahu M. Goldratt"],
    year: "1984",
    domain: "Operations & Process Management",
    keyContribution: "Theory of Constraints and operational bottleneck management",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Dependency Intelligence"],
    linkedFrameworks: ["theory-of-constraints"],
    linkedSignalCategories: ["Operational Bottleneck", "Dependency Conflict"],
    linkedSystemChains: ["sc-operational-bottleneck", "sc-dependency-intelligence"],
    tags: ["constraint", "throughput", "bottleneck", "five focusing steps"],
  },
  {
    id: "src-deming-oc",
    title: "Out of the Crisis",
    authors: ["W. Edwards Deming"],
    year: "1982",
    domain: "Operations & Process Management",
    keyContribution: "Quality management and statistical process control",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Maturity Scoring"],
    linkedFrameworks: ["statistical-process-control", "pdca-cycle", "total-quality-management"],
    linkedSignalCategories: ["Execution Breakdown", "Performance Degradation"],
    linkedSystemChains: ["sc-process-improvement", "sc-org-health"],
    tags: ["quality", "14 points", "SPC", "continuous improvement"],
  },
  {
    id: "src-womack-lt",
    title: "Lean Thinking",
    authors: ["James P. Womack", "Daniel T. Jones"],
    year: "1996",
    domain: "Operations & Process Management",
    keyContribution: "Core lean principles for process improvement across industries",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["lean", "value-stream-mapping"],
    linkedSignalCategories: ["Operational Bottleneck", "Capacity Overload"],
    linkedSystemChains: ["sc-operational-bottleneck", "sc-process-improvement"],
    tags: ["five lean principles", "waste", "flow", "pull", "perfection"],
  },
  {
    id: "src-george-lss",
    title: "The Lean Six Sigma Pocket Toolbook",
    authors: ["Michael George", "David Rowlands", "Mark Price", "John Maxey"],
    year: "2004",
    domain: "Operations & Process Management",
    keyContribution: "Lean Six Sigma methods for process improvement",
    diagnosticRelevance: ["Diagnosis", "Action Generation"],
    linkedFrameworks: ["six-sigma-dmaic", "lean", "statistical-process-control"],
    linkedSignalCategories: ["Execution Breakdown", "Operational Bottleneck"],
    linkedSystemChains: ["sc-process-improvement"],
    tags: ["DMAIC", "lean six sigma", "toolbox"],
  },
  {
    id: "src-pande-ssw",
    title: "Six Sigma Way",
    authors: ["Peter S. Pande", "Robert P. Neuman", "Roland R. Cavanagh"],
    year: "2000",
    domain: "Operations & Process Management",
    keyContribution: "Six Sigma approach to quality improvement",
    diagnosticRelevance: ["Diagnosis", "Action Generation"],
    linkedFrameworks: ["six-sigma-dmaic"],
    linkedSignalCategories: ["Execution Breakdown", "Performance Degradation"],
    linkedSystemChains: ["sc-process-improvement"],
    tags: ["six sigma", "DMAIC", "quality improvement"],
  },
  {
    id: "src-hammer-reengineer",
    title: "Reengineering the Corporation",
    authors: ["Michael Hammer", "James Champy"],
    year: "1993",
    domain: "Operations & Process Management",
    keyContribution: "Business process reengineering principles",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["business-process-reengineering"],
    linkedSignalCategories: ["Operational Bottleneck", "Execution Breakdown"],
    linkedSystemChains: ["sc-process-improvement", "sc-org-design"],
    tags: ["BPR", "radical redesign", "process transformation"],
  },
  {
    id: "src-chopra-scm",
    title: "Supply Chain Management: Strategy, Planning & Operation",
    authors: ["Sunil Chopra", "Peter Meindl"],
    year: "2001",
    domain: "Operations & Process Management",
    keyContribution: "End-to-end supply chain frameworks",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["sipoc-mapping", "value-stream-mapping"],
    linkedSignalCategories: ["Dependency Conflict", "Operational Bottleneck"],
    linkedSystemChains: ["sc-dependency-intelligence"],
    tags: ["supply chain", "logistics", "demand planning"],
  },
  {
    id: "src-besterfield-tqm",
    title: "Total Quality Management",
    authors: ["Dale H. Besterfield"],
    year: "2003",
    domain: "Operations & Process Management",
    keyContribution: "Integrating quality throughout organizations",
    diagnosticRelevance: ["Maturity Scoring", "Structural Remedy"],
    linkedFrameworks: ["total-quality-management"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-org-health", "sc-process-improvement"],
    tags: ["TQM", "quality culture", "customer focus"],
  },
  {
    id: "src-cox-toc-handbook",
    title: "The Theory of Constraints Handbook",
    authors: ["James Cox III", "John Schleier"],
    year: "2010",
    domain: "Operations & Process Management",
    keyContribution: "Comprehensive discussion of TOC methods",
    diagnosticRelevance: ["Diagnosis", "Dependency Intelligence"],
    linkedFrameworks: ["theory-of-constraints"],
    linkedSignalCategories: ["Operational Bottleneck", "Dependency Conflict"],
    linkedSystemChains: ["sc-operational-bottleneck", "sc-dependency-intelligence"],
    tags: ["TOC", "throughput accounting", "constraints"],
  },
];

// ── Domain 3: Project, Program & Portfolio Management ────────────────────

const PROJECT_SOURCES: CanonicalSource[] = [
  {
    id: "src-pmi-pmbok",
    title: "A Guide to the Project Management Body of Knowledge (PMBOK Guide)",
    authors: ["Project Management Institute"],
    year: "Latest edition",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Global standard for project management practices across 10 knowledge areas",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Action Generation"],
    linkedFrameworks: ["pmbok-knowledge-areas"],
    linkedSignalCategories: ["Milestone Delay", "Execution Breakdown", "Budget Variance"],
    linkedSystemChains: ["sc-initiative-health", "sc-execution-discipline"],
    tags: ["PMBOK", "WBS", "earned value", "risk management", "PMO"],
  },
  {
    id: "src-pmi-agile",
    title: "Agile Practice Guide",
    authors: ["Project Management Institute", "Agile Alliance"],
    year: "2017",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Comprehensive agile and hybrid project practices",
    diagnosticRelevance: ["Advisory", "Action Generation"],
    linkedFrameworks: ["pmbok-knowledge-areas"],
    linkedSignalCategories: ["Execution Breakdown"],
    linkedSystemChains: ["sc-execution-discipline", "sc-process-improvement"],
    tags: ["agile", "hybrid", "scrum", "kanban", "adaptive"],
  },
  {
    id: "src-sutherland-scrum",
    title: "Scrum: The Art of Doing Twice the Work in Half the Time",
    authors: ["Jeff Sutherland", "JJ Sutherland"],
    year: "2014",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Scrum framework for iterative development",
    diagnosticRelevance: ["Advisory", "Action Generation"],
    linkedFrameworks: ["pmbok-knowledge-areas"],
    linkedSignalCategories: ["Execution Breakdown", "Backlog Accumulation"],
    linkedSystemChains: ["sc-execution-velocity", "sc-execution-discipline"],
    tags: ["scrum", "sprints", "velocity", "retrospectives"],
  },
  {
    id: "src-goldratt-cc",
    title: "Critical Chain",
    authors: ["Eliyahu M. Goldratt"],
    year: "1997",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Critical chain scheduling to reduce delays through buffer management",
    diagnosticRelevance: ["Diagnosis", "Dependency Intelligence"],
    linkedFrameworks: ["critical-chain-pm", "theory-of-constraints"],
    linkedSignalCategories: ["Milestone Delay", "Dependency Conflict"],
    linkedSystemChains: ["sc-initiative-health", "sc-dependency-intelligence"],
    tags: ["critical chain", "buffer management", "CCPM"],
  },
  {
    id: "src-berkun-mth",
    title: "Making Things Happen",
    authors: ["Scott Berkun"],
    year: "2008",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Practical insights for managing technical projects",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["pmbok-knowledge-areas"],
    linkedSignalCategories: ["Execution Breakdown"],
    linkedSystemChains: ["sc-execution-discipline"],
    tags: ["project management", "leadership", "execution"],
  },
  {
    id: "src-levine-ppm",
    title: "Project Portfolio Management",
    authors: ["Harvey Levine"],
    year: "2005",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Guide to managing portfolios of projects",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Advisory"],
    linkedFrameworks: ["portfolio-prioritization-matrix"],
    linkedSignalCategories: ["Portfolio Imbalance"],
    linkedSystemChains: ["sc-initiative-portfolio"],
    tags: ["portfolio management", "prioritization", "resource allocation"],
  },
  {
    id: "src-fleming-evm",
    title: "Earned Value Management",
    authors: ["Quentin W. Fleming", "Joel M. Koppelman"],
    year: "2000",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Metrics for performance and progress measurement",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["pmbok-knowledge-areas"],
    linkedSignalCategories: ["Budget Variance", "Milestone Delay"],
    linkedSystemChains: ["sc-initiative-health", "sc-performance-management"],
    tags: ["EVM", "CPI", "SPI", "budget", "schedule"],
  },
  {
    id: "src-ries-lean-startup",
    title: "The Lean Startup",
    authors: ["Eric Ries"],
    year: "2011",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Applies iterative project principles to product and startup development",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["lean-startup"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-innovation-pipeline"],
    tags: ["MVP", "build-measure-learn", "pivoting", "validated learning"],
  },
  {
    id: "src-kim-phoenix",
    title: "The Phoenix Project",
    authors: ["Gene Kim", "Kevin Behr", "George Spafford"],
    year: "2013",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "DevOps and project flow improvement through the three ways",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["lean", "theory-of-constraints"],
    linkedSignalCategories: ["Execution Breakdown", "Operational Bottleneck"],
    linkedSystemChains: ["sc-execution-velocity", "sc-operational-bottleneck"],
    tags: ["DevOps", "flow", "WIP", "deployment frequency"],
  },
  {
    id: "src-anderson-kanban",
    title: "Kanban: Successful Evolutionary Change for Your Technology Business",
    authors: ["David J. Anderson"],
    year: "2010",
    domain: "Project, Program & Portfolio Management",
    keyContribution: "Kanban methods for flow optimization and evolutionary change",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["lean"],
    linkedSignalCategories: ["Backlog Accumulation", "Execution Breakdown"],
    linkedSystemChains: ["sc-execution-velocity"],
    tags: ["kanban", "WIP limits", "pull system", "flow"],
  },
];

// ── Domain 4: Finance & Accounting ───────────────────────────────────────

const FINANCE_SOURCES: CanonicalSource[] = [
  {
    id: "src-koller-val",
    title: "Valuation: Measuring and Managing the Value of Companies",
    authors: ["Tim Koller", "Marc Goedhart", "David Wessels"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Core corporate valuation principles and DCF methodology",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["npv", "irr"],
    linkedSignalCategories: ["Budget Variance"],
    linkedSystemChains: ["sc-resource-allocation"],
    tags: ["valuation", "DCF", "WACC", "enterprise value"],
  },
  {
    id: "src-ross-cf",
    title: "Corporate Finance",
    authors: ["Stephen Ross", "Randolph Westerfield", "Jeffrey Jaffe"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Foundations of financial decision making",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["npv", "irr", "payback-period"],
    linkedSignalCategories: ["Budget Variance"],
    linkedSystemChains: ["sc-resource-allocation"],
    tags: ["capital structure", "cost of capital", "investment decisions"],
  },
  {
    id: "src-subramanyam-fsa",
    title: "Financial Statement Analysis",
    authors: ["K. R. Subramanyam"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Interpreting and analyzing financial reports",
    diagnosticRelevance: ["Diagnosis", "Signal Detection"],
    linkedFrameworks: ["activity-based-costing"],
    linkedSignalCategories: ["Budget Variance", "Performance Degradation"],
    linkedSystemChains: ["sc-performance-management"],
    tags: ["ratio analysis", "financial health", "liquidity"],
  },
  {
    id: "src-damodaran-inv-val",
    title: "Investment Valuation",
    authors: ["Aswath Damodaran"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Techniques for valuing assets and businesses",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["npv", "real-options"],
    linkedSignalCategories: ["Budget Variance"],
    linkedSystemChains: ["sc-resource-allocation"],
    tags: ["valuation", "real options", "equity valuation"],
  },
  {
    id: "src-hull-risk",
    title: "Risk Management and Financial Institutions",
    authors: ["John C. Hull"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Risk measurement and financial risk management frameworks",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["monte-carlo-simulation", "enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation"],
    tags: ["VaR", "credit risk", "market risk", "hedging"],
  },
  {
    id: "src-thaler-bf",
    title: "Behavioral Finance",
    authors: ["Richard Thaler"],
    year: "Latest edition",
    domain: "Finance & Accounting",
    keyContribution: "Human behavior and cognitive biases in financial markets",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["cognitive-bias-codex", "prospect-theory"],
    linkedSignalCategories: ["Decision Bottleneck"],
    linkedSystemChains: ["sc-decision-support"],
    tags: ["behavioral economics", "nudging", "mental accounting"],
  },
];

// ── Domain 5: Marketing, Sales & Customer Strategy ───────────────────────

const MARKETING_SOURCES: CanonicalSource[] = [
  {
    id: "src-kotler-mm",
    title: "Marketing Management",
    authors: ["Philip Kotler", "Kevin Lane Keller"],
    year: "Latest edition",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Comprehensive marketing principles and strategic frameworks",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["marketing-mix-4ps", "customer-journey-mapping"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["STP", "4Ps", "brand management", "marketing strategy"],
  },
  {
    id: "src-cialdini-influence",
    title: "Influence: The Psychology of Persuasion",
    authors: ["Robert Cialdini"],
    year: "1984",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Six psychological principles that drive buying and compliance behavior",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["nudge-theory", "fogg-behavior-model"],
    linkedSignalCategories: ["Leadership Bandwidth"],
    linkedSystemChains: ["sc-change-management"],
    tags: ["persuasion", "reciprocity", "scarcity", "social proof"],
  },
  {
    id: "src-moore-crossing",
    title: "Crossing the Chasm",
    authors: ["Geoffrey Moore"],
    year: "Latest edition",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Technology adoption lifecycle and crossing the chasm to mainstream markets",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["disruptive-innovation-model"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-innovation-pipeline"],
    tags: ["technology adoption", "early majority", "chasm", "market entry"],
  },
  {
    id: "src-kim-bos2",
    title: "Blue Ocean Shift",
    authors: ["W. Chan Kim", "Renée Mauborgne"],
    year: "2017",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Creating new market space and non-competitive demand",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["blue-ocean-strategy"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-innovation-pipeline"],
    tags: ["value innovation", "market creation", "ERRC grid"],
  },
  {
    id: "src-osterwalder-vpd",
    title: "Value Proposition Design",
    authors: ["Alexander Osterwalder", "Yves Pigneur"],
    year: "2014",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Crafting compelling value propositions matched to customer needs",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["value-proposition-canvas", "jobs-to-be-done"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["value proposition", "customer jobs", "pain relievers", "gain creators"],
  },
  {
    id: "src-dixon-challenger",
    title: "The Challenger Sale",
    authors: ["Matthew Dixon", "Brent Adamson"],
    year: "2011",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Sales approach focused on challenging customer thinking and teaching insights",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["jobs-to-be-done"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-strategic-alignment"],
    tags: ["challenger", "insight selling", "commercial teaching"],
  },
  {
    id: "src-ariely-pi",
    title: "Predictably Irrational",
    authors: ["Dan Ariely"],
    year: "2008",
    domain: "Marketing, Sales & Customer Strategy",
    keyContribution: "Insights into consumer irrational behavior and decision patterns",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["prospect-theory", "nudge-theory"],
    linkedSignalCategories: ["Decision Bottleneck"],
    linkedSystemChains: ["sc-decision-support"],
    tags: ["behavioral economics", "anchoring", "irrational decisions"],
  },
];

// ── Domain 6: Human Capital & Organization ───────────────────────────────

const PEOPLE_SOURCES: CanonicalSource[] = [
  {
    id: "src-drucker-pm",
    title: "The Practice of Management",
    authors: ["Peter Drucker"],
    year: "1954",
    domain: "Human Capital & Organization",
    keyContribution: "Foundation of modern management principles including MBO",
    diagnosticRelevance: ["Signal Detection", "Diagnosis", "Advisory"],
    linkedFrameworks: ["balanced-scorecard", "okr-alignment"],
    linkedSignalCategories: ["Strategic Misalignment", "Leadership Bandwidth"],
    linkedSystemChains: ["sc-strategic-alignment", "sc-leadership-bandwidth"],
    tags: ["MBO", "management functions", "purpose", "performance"],
  },
  {
    id: "src-drucker-mc21",
    title: "Management Challenges for the 21st Century",
    authors: ["Peter Drucker"],
    year: "1999",
    domain: "Human Capital & Organization",
    keyContribution: "Management in dynamic, knowledge-worker-driven environments",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["span-of-control"],
    linkedSignalCategories: ["Leadership Bandwidth"],
    linkedSystemChains: ["sc-leadership-bandwidth", "sc-org-design"],
    tags: ["knowledge work", "self-management", "change management"],
  },
  {
    id: "src-kotter-lc",
    title: "Leading Change",
    authors: ["John Kotter"],
    year: "1996",
    domain: "Human Capital & Organization",
    keyContribution: "Eight-step framework for successful organizational change",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["kotter-8-step"],
    linkedSignalCategories: ["Change Initiative"],
    linkedSystemChains: ["sc-change-management"],
    tags: ["change management", "urgency", "coalition", "transformation"],
  },
  {
    id: "src-lencioni-5d",
    title: "The Five Dysfunctions of a Team",
    authors: ["Patrick Lencioni"],
    year: "2002",
    domain: "Human Capital & Organization",
    keyContribution: "Pyramid model of team dysfunctions and how to resolve them",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["tuckman-team-model"],
    linkedSignalCategories: ["Department Coordination Failure"],
    linkedSystemChains: ["sc-cross-department"],
    tags: ["team trust", "conflict", "commitment", "accountability"],
  },
  {
    id: "src-pink-drive",
    title: "Drive: The Surprising Truth About What Motivates Us",
    authors: ["Daniel Pink"],
    year: "2009",
    domain: "Human Capital & Organization",
    keyContribution: "Intrinsic motivation science: autonomy, mastery, purpose",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["fogg-behavior-model", "com-b-model"],
    linkedSignalCategories: ["Capacity Overload", "Execution Breakdown"],
    linkedSystemChains: ["sc-org-capacity", "sc-change-management"],
    tags: ["motivation", "autonomy", "mastery", "purpose", "intrinsic"],
  },
  {
    id: "src-galbraith-od",
    title: "Principles of Organizational Design",
    authors: ["Jay Galbraith"],
    year: "1973",
    domain: "Human Capital & Organization",
    keyContribution: "Star Model design choices for organizational structures",
    diagnosticRelevance: ["Diagnosis", "Structural Remedy"],
    linkedFrameworks: ["galbraith-star-model"],
    linkedSignalCategories: ["Department Coordination Failure"],
    linkedSystemChains: ["sc-org-design"],
    tags: ["star model", "structure", "processes", "people", "rewards"],
  },
  {
    id: "src-charan-lp",
    title: "The Leadership Pipeline",
    authors: ["Ram Charan", "Stephen Drotter", "James Noel"],
    year: "2001",
    domain: "Human Capital & Organization",
    keyContribution: "Leadership development framework across organizational levels",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["leadership-pipeline"],
    linkedSignalCategories: ["Leadership Bandwidth"],
    linkedSystemChains: ["sc-leadership-bandwidth"],
    tags: ["leadership development", "succession", "capability building"],
  },
  {
    id: "src-goleman-ei",
    title: "Emotional Intelligence",
    authors: ["Daniel Goleman"],
    year: "1995",
    domain: "Human Capital & Organization",
    keyContribution: "Emotional competencies for workplace performance and leadership",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["emotional-intelligence"],
    linkedSignalCategories: ["Leadership Bandwidth", "Department Coordination Failure"],
    linkedSystemChains: ["sc-leadership-bandwidth", "sc-cross-department"],
    tags: ["EQ", "self-awareness", "empathy", "social skills"],
  },
  {
    id: "src-mcchrystal-tot",
    title: "Team of Teams",
    authors: ["General Stanley McChrystal"],
    year: "2015",
    domain: "Human Capital & Organization",
    keyContribution: "Networked teamwork and shared consciousness in complex environments",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["organizational-network-analysis"],
    linkedSignalCategories: ["Department Coordination Failure"],
    linkedSystemChains: ["sc-cross-department"],
    tags: ["agility", "decentralization", "shared consciousness", "networks"],
  },
  {
    id: "src-coyle-cc",
    title: "The Culture Code",
    authors: ["Daniel Coyle"],
    year: "2018",
    domain: "Human Capital & Organization",
    keyContribution: "Three core skills that make highly successful organizational cultures",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["cultural-web"],
    linkedSignalCategories: ["Department Coordination Failure", "Change Initiative"],
    linkedSystemChains: ["sc-change-management"],
    tags: ["psychological safety", "vulnerability", "purpose", "culture"],
  },
  {
    id: "src-bock-wr",
    title: "Work Rules!",
    authors: ["Laszlo Bock"],
    year: "2015",
    domain: "Human Capital & Organization",
    keyContribution: "People operations practices from Google — data-driven HR",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["span-of-control"],
    linkedSignalCategories: ["Capacity Overload"],
    linkedSystemChains: ["sc-org-capacity", "sc-workforce-intelligence"],
    tags: ["people analytics", "psychological safety", "hiring", "performance"],
  },
];

// ── Domain 7: Technology, Data & Digital Transformation ──────────────────

const TECHNOLOGY_SOURCES: CanonicalSource[] = [
  {
    id: "src-weill-iteag",
    title: "Enterprise Architecture as Strategy",
    authors: ["Jeanne W. Ross", "Peter Weill", "David Robertson"],
    year: "2006",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Architecture frameworks linking IT capabilities and business strategy",
    diagnosticRelevance: ["Diagnosis", "Structural Remedy"],
    linkedFrameworks: ["cobit", "itil"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-it-governance"],
    tags: ["enterprise architecture", "operating models", "IT strategy"],
  },
  {
    id: "src-weill-itgov",
    title: "IT Governance",
    authors: ["Peter Weill", "Jeanne Ross"],
    year: "2004",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "IT governance frameworks for decision rights and accountability",
    diagnosticRelevance: ["Diagnosis", "Advisory"],
    linkedFrameworks: ["cobit"],
    linkedSignalCategories: ["Strategic Misalignment"],
    linkedSystemChains: ["sc-it-governance"],
    tags: ["IT governance", "decision rights", "accountability"],
  },
  {
    id: "src-axelos-itil",
    title: "ITIL® Service Lifecycle",
    authors: ["AXELOS"],
    year: "Latest edition",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Best practices for IT service management",
    diagnosticRelevance: ["Structural Remedy"],
    linkedFrameworks: ["itil"],
    linkedSignalCategories: ["Execution Breakdown"],
    linkedSystemChains: ["sc-it-governance"],
    tags: ["ITIL", "service management", "incident management", "ITSM"],
  },
  {
    id: "src-isaca-cobit",
    title: "COBIT® 2019 Framework",
    authors: ["ISACA"],
    year: "Latest edition",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Governance and management of enterprise IT",
    diagnosticRelevance: ["Diagnosis", "Maturity Scoring"],
    linkedFrameworks: ["cobit"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-it-governance"],
    tags: ["COBIT", "IT governance", "risk", "compliance"],
  },
  {
    id: "src-rogers-dtp",
    title: "Digital Transformation Playbook",
    authors: ["David Rogers"],
    year: "2016",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Five domains of digital transformation strategy",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["disruptive-innovation-model"],
    linkedSignalCategories: ["Strategic Opportunity"],
    linkedSystemChains: ["sc-innovation-pipeline"],
    tags: ["digital transformation", "platform", "data", "customer"],
  },
  {
    id: "src-davenport-analytics",
    title: "Analytics at Work",
    authors: ["Thomas H. Davenport", "Jeanne G. Harris", "Robert Morison"],
    year: "2010",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Using analytics to improve organizational decision making",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["statistical-process-control"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-predictive-analytics"],
    tags: ["analytics", "decision support", "data-driven management"],
  },
  {
    id: "src-provost-dsb",
    title: "Data Science for Business",
    authors: ["Foster Provost", "Tom Fawcett"],
    year: "2013",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Foundational principles of data-driven decision-making",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["statistical-process-control"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-predictive-analytics"],
    tags: ["data mining", "predictive analytics", "machine learning", "business decisions"],
  },
  {
    id: "src-siegel-pa",
    title: "Predictive Analytics",
    authors: ["Eric Siegel"],
    year: "2013",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Concepts and business applications of predictive modeling",
    diagnosticRelevance: ["Signal Detection", "Advisory"],
    linkedFrameworks: ["monte-carlo-simulation"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-predictive-analytics"],
    tags: ["predictive modeling", "machine learning", "forecasting"],
  },
  {
    id: "src-ng-mly",
    title: "Machine Learning Yearning",
    authors: ["Andrew Ng"],
    year: "2018",
    domain: "Technology, Data & Digital Transformation",
    keyContribution: "Practical AI project development guidance",
    diagnosticRelevance: ["Advisory"],
    linkedFrameworks: ["statistical-process-control"],
    linkedSignalCategories: ["Performance Degradation"],
    linkedSystemChains: ["sc-predictive-analytics", "sc-knowledge-intelligence"],
    tags: ["machine learning", "AI", "project structure", "error analysis"],
  },
];

// ── Domain 8: Risk, Compliance & Governance ──────────────────────────────

const RISK_SOURCES: CanonicalSource[] = [
  {
    id: "src-lam-erm",
    title: "Enterprise Risk Management",
    authors: ["James Lam"],
    year: "2003",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Frameworks for managing enterprise-level risks comprehensively",
    diagnosticRelevance: ["Signal Detection", "Diagnosis"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation", "sc-governance-risk"],
    tags: ["ERM", "risk culture", "risk appetite", "three lines of defense"],
  },
  {
    id: "src-coso-erm",
    title: "COSO® Enterprise Risk Management",
    authors: ["COSO"],
    year: "Latest edition",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Standard integrated model for enterprise risk management",
    diagnosticRelevance: ["Signal Detection", "Structural Remedy"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation", "sc-governance-risk"],
    tags: ["COSO", "ERM", "internal control", "risk integration"],
  },
  {
    id: "src-iso-31000",
    title: "ISO 31000:2018 Risk Management",
    authors: ["ISO"],
    year: "Latest edition",
    domain: "Risk, Compliance & Governance",
    keyContribution: "International principles and guidelines for risk management",
    diagnosticRelevance: ["Structural Remedy", "Maturity Scoring"],
    linkedFrameworks: ["iso-31000"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation"],
    tags: ["ISO 31000", "risk principles", "risk process", "risk context"],
  },
  {
    id: "src-iso-27001",
    title: "ISO/IEC 27001:2022 Information Security",
    authors: ["ISO"],
    year: "Latest edition",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Standard for information security management systems",
    diagnosticRelevance: ["Structural Remedy"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-governance-risk", "sc-it-governance"],
    tags: ["ISMS", "information security", "ISO 27001"],
  },
  {
    id: "src-fink-crisis",
    title: "Crisis Management: Planning for the Inevitable",
    authors: ["Steven Fink"],
    year: "1986",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Crisis response planning and four stages of crisis lifecycle",
    diagnosticRelevance: ["Advisory", "Signal Detection"],
    linkedFrameworks: ["enterprise-risk-management", "bowtie-risk"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation"],
    tags: ["crisis planning", "risk communication", "prodromal", "crisis team"],
  },
  {
    id: "src-monks-cg",
    title: "Corporate Governance",
    authors: ["Robert Monks", "Nell Minow"],
    year: "1995",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Corporate governance principles and accountability structures",
    diagnosticRelevance: ["Structural Remedy"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["Decision Bottleneck"],
    linkedSystemChains: ["sc-governance-risk"],
    tags: ["corporate governance", "board accountability", "shareholder value"],
  },
  {
    id: "src-sox",
    title: "Sarbanes-Oxley Act (SOX) Compliance Framework",
    authors: ["U.S. Congress"],
    year: "2002",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Financial reporting and internal control regulations for public companies",
    diagnosticRelevance: ["Signal Detection", "Structural Remedy"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-governance-risk"],
    tags: ["SOX", "financial controls", "audit", "internal controls"],
  },
  {
    id: "src-gdpr",
    title: "GDPR",
    authors: ["European Parliament"],
    year: "2016",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Data protection and privacy standards for organizations",
    diagnosticRelevance: ["Signal Detection", "Structural Remedy"],
    linkedFrameworks: ["enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-governance-risk", "sc-it-governance"],
    tags: ["data privacy", "GDPR", "compliance", "personal data"],
  },
  {
    id: "src-hiles-bcm",
    title: "Business Continuity Management",
    authors: ["Andrew Hiles"],
    year: "2010",
    domain: "Risk, Compliance & Governance",
    keyContribution: "Frameworks for organizational resilience and continuity planning",
    diagnosticRelevance: ["Advisory", "Structural Remedy"],
    linkedFrameworks: ["iso-31000", "enterprise-risk-management"],
    linkedSignalCategories: ["High Risk Indicator"],
    linkedSystemChains: ["sc-risk-escalation"],
    tags: ["BCM", "business continuity", "disaster recovery", "resilience"],
  },
];

// ── Master Registry ──────────────────────────────────────────────────────

export const KNOWLEDGE_SUPERBASE: CanonicalSource[] = [
  ...STRATEGY_SOURCES,
  ...OPERATIONS_SOURCES,
  ...PROJECT_SOURCES,
  ...FINANCE_SOURCES,
  ...MARKETING_SOURCES,
  ...PEOPLE_SOURCES,
  ...TECHNOLOGY_SOURCES,
  ...RISK_SOURCES,
];

// ── Best Practices Derived from Superbase ────────────────────────────────

export const BEST_PRACTICES: BestPractice[] = [
  {
    id: "bp-001",
    title: "Align all initiatives to strategic pillars before approving",
    description: "Every initiative must trace to at least one strategic pillar. Uninvested initiatives without alignment should be paused or cancelled.",
    domain: "Corporate Strategy & Leadership",
    frameworks: ["balanced-scorecard", "okr-alignment", "strategy-kernel"],
    applicableTo: ["Initiatives", "Dashboard"],
    evidence: "Kaplan & Norton (1996); Lafley & Martin (2013)",
  },
  {
    id: "bp-002",
    title: "Identify the system constraint before adding capacity",
    description: "Adding resources to a non-constraint yields no throughput improvement. Always identify the binding constraint first (TOC).",
    domain: "Operations & Process Management",
    frameworks: ["theory-of-constraints", "value-stream-mapping"],
    applicableTo: ["Departments", "Action Items"],
    evidence: "Goldratt (1984); Womack & Jones (1996)",
  },
  {
    id: "bp-003",
    title: "Use earned value metrics for early warning on projects",
    description: "CPI < 0.9 or SPI < 0.9 are early warning signals. Do not wait for milestone misses to intervene.",
    domain: "Project, Program & Portfolio Management",
    frameworks: ["pmbok-knowledge-areas", "critical-path-method"],
    applicableTo: ["Initiatives", "Dashboard"],
    evidence: "Fleming & Koppelman (2000); PMI PMBOK",
  },
  {
    id: "bp-004",
    title: "Limit work-in-progress to increase throughput",
    description: "WIP limits reduce context switching, expose bottlenecks, and increase flow efficiency.",
    domain: "Operations & Process Management",
    frameworks: ["lean", "theory-of-constraints"],
    applicableTo: ["Action Items", "Departments"],
    evidence: "Anderson (2010); Goldratt (1997)",
  },
  {
    id: "bp-005",
    title: "Run retrospectives after every major initiative phase",
    description: "Systematic lessons-learned capture compounding organizational improvement.",
    domain: "Project, Program & Portfolio Management",
    frameworks: ["kaizen", "pdca-cycle"],
    applicableTo: ["Initiatives", "Knowledge"],
    evidence: "Derby & Larsen (2006); Liker (2004)",
  },
  {
    id: "bp-006",
    title: "Segment leadership risk from operational risk",
    description: "Decision bottlenecks at leadership level must be treated as structural issues, not individual performance issues.",
    domain: "Human Capital & Organization",
    frameworks: ["span-of-control", "leadership-pipeline"],
    applicableTo: ["Team", "Departments"],
    evidence: "Charan et al. (2001); Galbraith (1973)",
  },
  {
    id: "bp-007",
    title: "Use scenario planning for high-uncertainty strategic decisions",
    description: "Single-point forecasting is insufficient for major commitments. Build 3 scenarios: optimistic, base, pessimistic.",
    domain: "Corporate Strategy & Leadership",
    frameworks: ["scenario-planning", "monte-carlo-simulation"],
    applicableTo: ["Advisory", "Reports"],
    evidence: "Ringland (1998); Raynor (2007)",
  },
  {
    id: "bp-008",
    title: "Apply the 8-step change model for structural transformations",
    description: "Structural changes without proper change management fail 70% of the time. Follow Kotter's sequence.",
    domain: "Human Capital & Organization",
    frameworks: ["kotter-8-step", "adkar"],
    applicableTo: ["Departments", "Initiatives"],
    evidence: "Kotter (1996)",
  },
];

// ── Lessons Learned Registry ──────────────────────────────────────────────

export const LESSONS_LEARNED: KnowledgeLesson[] = [
  {
    id: "ll-001",
    sourceId: "src-goldratt-goal",
    lesson: "Adding resources to a bottleneck process yields disproportionate throughput improvements. Ignoring the constraint wastes investment.",
    applicableTo: ["Departments", "Initiatives", "Action Items"],
    addedAt: "2025-01-01",
  },
  {
    id: "ll-002",
    sourceId: "src-kaplan-bsc",
    lesson: "Organizations that measure only financial KPIs miss 75% of leading indicators. Customer, internal process, and learning metrics are equally critical.",
    applicableTo: ["Dashboard", "Reports", "Diagnostics"],
    addedAt: "2025-01-01",
  },
  {
    id: "ll-003",
    sourceId: "src-kotter-lc",
    lesson: "Most change failures happen because of insufficient urgency or a weak guiding coalition — not poor execution planning.",
    applicableTo: ["Initiatives", "Departments"],
    addedAt: "2025-01-01",
  },
  {
    id: "ll-004",
    sourceId: "src-pmi-pmbok",
    lesson: "Projects that skip proper risk identification in the first two weeks average 40% higher cost overruns.",
    applicableTo: ["Initiatives", "Dashboard"],
    addedAt: "2025-01-01",
  },
  {
    id: "ll-005",
    sourceId: "src-lencioni-5d",
    lesson: "Team dysfunction is cumulative. Absence of trust at the base invalidates all performance improvements at higher levels.",
    applicableTo: ["Team", "Departments"],
    addedAt: "2025-01-01",
  },
  {
    id: "ll-006",
    sourceId: "src-rumelt-gsbs",
    lesson: "Bad strategy often masquerades as good strategy by using lofty goals without a clear diagnosis or coherent action plan.",
    applicableTo: ["Advisory", "Initiatives"],
    addedAt: "2025-01-01",
  },
];

// ── Query Helpers ────────────────────────────────────────────────────────

/**
 * [Apphia.Logic] Get all sources that inform a specific diagnostic relevance role
 */
export function getSourcesByDiagnosticRole(role: DiagnosticRelevance): CanonicalSource[] {
  return KNOWLEDGE_SUPERBASE.filter(s => s.diagnosticRelevance.includes(role));
}

/**
 * [Apphia.Logic] Get sources linked to a specific signal category
 */
export function getSourcesBySignalCategory(category: string): CanonicalSource[] {
  return KNOWLEDGE_SUPERBASE.filter(s => s.linkedSignalCategories.includes(category));
}

/**
 * [Apphia.Logic] Get sources linked to a specific framework
 */
export function getSourcesByFramework(frameworkId: string): CanonicalSource[] {
  return KNOWLEDGE_SUPERBASE.filter(s => s.linkedFrameworks.includes(frameworkId));
}

/**
 * [Apphia.Logic] Get all sources for a domain
 */
export function getSourcesByDomain(domain: KnowledgeDomain): CanonicalSource[] {
  return KNOWLEDGE_SUPERBASE.filter(s => s.domain === domain);
}

/**
 * [Apphia.Logic] Get best practices applicable to a module
 */
export function getBestPracticesForModule(module: string): BestPractice[] {
  return BEST_PRACTICES.filter(bp => bp.applicableTo.includes(module));
}

/**
 * [Apphia.Logic] Get lessons learned applicable to a module
 */
export function getLessonsForModule(module: string): KnowledgeLesson[] {
  return LESSONS_LEARNED.filter(ll => ll.applicableTo.includes(module));
}

/**
 * [Apphia.Logic] Get a summary of the knowledge superbase
 */
export function getKnowledgeSuperbaseSummary() {
  const domainCounts = KNOWLEDGE_SUPERBASE.reduce((acc, source) => {
    acc[source.domain] = (acc[source.domain] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return {
    totalSources: KNOWLEDGE_SUPERBASE.length,
    totalBestPractices: BEST_PRACTICES.length,
    totalLessonsLearned: LESSONS_LEARNED.length,
    domainCounts,
    uniqueFrameworksCovered: [...new Set(KNOWLEDGE_SUPERBASE.flatMap(s => s.linkedFrameworks))].length,
    uniqueSignalCategoriesCovered: [...new Set(KNOWLEDGE_SUPERBASE.flatMap(s => s.linkedSignalCategories))].length,
  };
}
